version: '3'
services:
  nginx:
    restart: always
    image: nginx:1.16.0
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/ssl:/ssl
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/pages:/usr/share/nginx/html
